using System;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using SBS_BarthLogistic.Classes;
using SBS_BarthLogistic.Parameters;

namespace SBS_BarthLogistic.OtherForms
{
    public partial class ImportRealToCarmForm : XtraForm
    {
        public ImportRealToCarmForm()
        {
            InitializeComponent();
        }

        void ImporRealToCarmForm_Load(object sender, EventArgs e)
        {
            paCarm1.ChangeFonts();
            txtData.SetDateFormat();
        }

        void btnAdd_Click(object sender, EventArgs e)
        {
            var spAll = new CLSSpAll(paCarm1, "spImportRealToCarm");
            spAll.AddParameter("D1", txtData.DateTime);
            spAll.AddParameter("UN", GlobalParameters.UserName);
            spAll.AddParameter("IdCarmT", DefaultValues.IdCarmT);
            spAll.Exceute();

            if (chbAutoCarm2.Checked)
            {
                SQL.Execute("DELETE FROM Carm2 WHERE IdCarm1 IN (SELECT IdCarm1 From Carm1 WHERE Data='" +
                            txtData.DateTime.ToString(GlobalParameters.ServerDateFormat) +
                            "' AND IsAutoGenerated = 1)");
                ProceduresClass.spCalcCarm("spCalcCarm2", txtData.DateTime);
            }

            DialogResult = DialogResult.OK;
        }
    }
}