using System;
using DevExpress.XtraEditors;
using SBS_BarthLogistic.Classes;

namespace SBS_BarthLogistic.OtherForms
{
    public partial class InsertToCarmFromCalc : XtraForm
    {
        readonly bool fillDetail;
        readonly int idCarm1;
        readonly string idProd;

        public InsertToCarmFromCalc(int idCarm1, string idProd, bool silent)
        {
            fillDetail = silent;
            this.idCarm1 = idCarm1;
            this.idProd = idProd;
            InitializeComponent();
        }

        void InsertToCarmFromCalc_Load(object sender, EventArgs e)
        {
            cbCalc.FillDataToLookUpEditAndSetFont("Calc", " WHERE IdProd=N'" + idProd + "'");
            if (fillDetail)
            {
                btnExport_Click(sender, e);
            }
        }

        void btnClose_Click(object sender, EventArgs e)
        {
            Close();
        }

        void btnExport_Click(object sender, EventArgs e)
        {
            if (InterfaceParameters.CheckNashti)
            {
                var dttb = SQL.Select(
                    " DECLARE @CarmRaod NUMERIC(12,3) DECLARE @IdProek int  SELECT  @CarmRaod=CarmRaod,@IdProek=IdProek From Carm1 WHERE IdCarm1=" +
                    idCarm1 +
                    " SELECT IdProd+',  '+Prod Prod,dbo.udfProdNashti(Idprod,@IdProek,GetDate())- @CarmRaod*DanakRaod/CarmRaod Raod" +
                    " FROM CalcProdView WHERE IdCalc = " + cbCalc.EditValue +
                    " AND saccontrol=1 GROUP By IdProd,Prod,DanakRaod,CarmRaod HAVING (dbo.udfProdNashti(Idprod,@IdProek,GetDate())- @CarmRaod*DanakRaod/CarmRaod)<0");

                if ((double)dttb.Rows.Count > 0)
                {
                    var msg = "";
                    for (var i = 0; i < dttb.Rows.Count; i++)
                    {
                        msg += dttb.Rows[i]["Prod"] + ", \n";
                    }
                    XtraMessageBox.Show("არ რის საკმარისი ნაშთი პროდუქციაზე: " + msg);
                    return;
                }
            }

            SQL.Execute(" DECLARE @CarmRaod NUMERIC(12,3) SELECT  @CarmRaod=CarmRaod From Carm1 WHERE IdCarm1=" +
                        idCarm1 +
                        " INSERT INTO Carm2(IsAutoGenerated, IdCarm1, IdProd, Raod, UN, CD)" +
                        "SELECT 1, " + idCarm1 + ", IdProd, @CarmRaod*DanakRaod/CarmRaod,  N'" +
                        GlobalParameters.UserName + "', GETDATE() " +
                        " FROM CalcProdView WHERE IdCalc = " + cbCalc.EditValue);
            Close();
        }
    }
}